"""Rename domains -> services

Revision ID: 085ac51f11b9
Revises: 6c6688d96548
Create Date: 2020-05-10 19:22:28.501675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '085ac51f11b9'
down_revision = '6c6688d96548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__services')),
    sa.UniqueConstraint('name', name=op.f('uq__services'))
    )
    op.drop_table('domains')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='domains_pkey'),
    sa.UniqueConstraint('name', name='uq__domains')
    )
    op.drop_table('services')
    # ### end Alembic commands ###
